/*
 * Copyright 2017 Axway Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test axway-java-test using AI Type  and AI Model

ROOST_METHOD_HASH=isDynamicReading_7afa5b766e
ROOST_METHOD_SIG_HASH=isDynamicReading_53ba50de05

"""
Scenario 1: Validate the true return value of method isDynamicReading

Details:
    TestName: testIsDynamicReadingWhenTrue
    Description: The test is meant to check if the method 'isDynamicReading' properly returns true when dynamicReading is set to true.

Execution:
    Arrange: Initialize a new ReadingBean and set its dynamicReading value to true.
    Act: Invoke the 'isDynamicReading' method.
    Assert: Verify the return value to be true.

Validation:
    The expected result is true because the value of dynamicReading was set to true. This validation ensures that the correct value of dynamicReading is returned when it's set to true.

Scenario 2: Validate the false return value of method isDynamicReading

Details:
    TestName: testIsDynamicReadingWhenFalse
    Description: The test is meant to check if the method 'isDynamicReading' properly returns false when dynamicReading is set to false.

Execution:
    Arrange: Initialize a new ReadingBean and set its dynamicReading value to false.
    Act: Invoke the 'isDynamicReading' method.
    Assert: Verify the return value to be false.

Validation:
    The expected result is false because the value of dynamicReading was set to false. This validation ensures that the correct value of dynamicReading is returned when it's set to false.

Scenario 3: Validate the initial value of method isDynamicReading

Details:
    TestName: testIsDynamicReadingInitialValue
    Description: This test is meant to check if the method 'isDynamicReading' properly returns the initial value of dynamicReading when no value has been set.

Execution:
    Arrange: Initialize a new ReadingBean without setting dynamicReading.
    Act: Invoke the 'isDynamicReading' method.
    Assert: Verify the return value to be the default initial value of a boolean (which should be false).

Validation:
    The expected result is false because it's the initial value of a boolean attribute when not set. This validation ensures that the function works properly, in the context of unfilled attributes.
"""
*/

// ********RoostGPT********

package com.axway.ats.common.performance.monitor.beans;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;
import com.axway.ats.common.PublicAtsApi;

@Tag("integration")
public class ReadingBeanIsDynamicReadingTest {

	@Test
	@Tag("valid")
	public void testIsDynamicReadingWhenTrue() {
		// Arrange
		ReadingBean bean = new ReadingBean();
		bean.setDynamicReading(true);
		// Act
		boolean result = bean.isDynamicReading();
		// Assert
		assertTrue(result, "Expected dynamicReading to be true");
	}

	@Test
	@Tag("valid")
	public void testIsDynamicReadingWhenFalse() {
		// Arrange
		ReadingBean bean = new ReadingBean();
		bean.setDynamicReading(false);
		// Act
		boolean result = bean.isDynamicReading();
		// Assert
		assertFalse(result, "Expected dynamicReading to be false");
	}

	@Test
	@Tag("boundary")
	public void testIsDynamicReadingInitialValue() {
		// Arrange
		ReadingBean bean = new ReadingBean();
		// Act
		boolean result = bean.isDynamicReading();
		// Assert
		assertFalse(result, "Expected initial dynamicReading value to be false");
	}

}