/*
 * Copyright 2017 Axway Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test axway-java-test using AI Type  and AI Model

ROOST_METHOD_HASH=getFirstAtsAgent_9ded35b35a
ROOST_METHOD_SIG_HASH=getFirstAtsAgent_9160efdd0c

Scenario 1: Testing retrieval of first ATS agent when an agent is set

  Details:
    TestName: testGetFirstAtsAgentWhenAnAgentIsSet.
    Description: This test is intended to check if the method getFirstAtsAgent() correctly retrieves and returns the first ATS agent that was previously set using the setFirstAtsAgent() method of the same class.
  Execution:
    Arrange: Create a FileSystemEqualityState object and use setFirstAtsAgent() to set a value for the first ATS agent.
    Act: Call the getFirstAtsAgent() method.
    Assert: Check if the returned value is equal to the set value.
  Validation:
    The test aims to verify that the value returned by the getFirstAtsAgent() method corresponds to the value that was set. This means that the class is correctly storing and retrieving the first ATS agent.

Scenario 2: Testing retrieval of first ATS agent when no agent is set

  Details:
    TestName: testGetFirstAtsAgentWhenNoAgentIsSet.
    Description: This test is meant to check the behavior of the getFirstAtsAgent() method when no value for the first ATS agent has been set.
  Execution:
    Arrange: Create a FileSystemEqualityState object without setting a value for the first ATS agent.
    Act: Call the getFirstAtsAgent() method.
    Assert: Check if the returned value is null or a predefined default value.
  Validation:
    This test verifies that the getFirstAtsAgent() method correctly returns null or a predefined default value when no value for the first ATS agent has been set. This behavior is important, as it denotes the absence of a value for the agent.

Scenario 3: Testing retrieval of first ATS agent when it's set multiple times

  Details:
    TestName: testGetFirstAtsAgentWhenSetMultipleTimes.
    Description: This test is meant to check getFirstAtsAgent() method behaviour when the first ATS agent is set multiple times.
  Execution:
    Arrange: Create a FileSystemEqualityState object and use setFirstAtsAgent() to set a value for the first ATS agent several times.
    Act: Call the getFirstAtsAgent() method.
    Assert: Check if the returned value is equal to the last set value.
  Validation:
    This test aims to verify if the getFirstAtsAgent() method always returns the most recent value set. This indicates that a previous value is correctly replaced whenever a new value for the first ATS agent is set.

Note: The specs do not provide specific details about whether accessing the first ATS agent should trigger any changes to the system state, whether multiple calls should return the same value, or how it should handle concurrent access. If such behaviors are part of the system requirements, additional tests would be needed to verify them.
*/

// ********RoostGPT********

package com.axway.ats.common.filesystem.snapshot.equality;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import com.axway.ats.common.filesystem.snapshot.equality.FileSystemEqualityState;
import org.junit.jupiter.api.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.axway.ats.common.PublicAtsApi;

@Tag("valid")
public class FileSystemEqualityStateGetFirstAtsAgentTest {

	@Test
	public void testGetFirstAtsAgentWhenAnAgentIsSet() {
		// arrange
		FileSystemEqualityState fileSystemEqualityState = new FileSystemEqualityState("snapshot1", "snapshot2");
		fileSystemEqualityState.setFirstAtsAgent("127.0.0.1");
		// act
		String firstAtsAgent = fileSystemEqualityState.getFirstAtsAgent();
		// assert
		assertEquals("127.0.0.1", firstAtsAgent);
	}

	@Test
	@Tag("boundary")
	public void testGetFirstAtsAgentWhenNoAgentIsSet() {
		// arrange
		FileSystemEqualityState fileSystemEqualityState = new FileSystemEqualityState("snapshot1", "snapshot2");
		// act
		String firstAtsAgent = fileSystemEqualityState.getFirstAtsAgent();
		// assert
		assertNull(firstAtsAgent);
	}

	@Test
	@Tag("invalid")
	public void testGetFirstAtsAgentWhenSetMultipleTimes() {
		// arrange
		FileSystemEqualityState fileSystemEqualityState = new FileSystemEqualityState("snapshot1", "snapshot2");
		fileSystemEqualityState.setFirstAtsAgent("127.0.0.1");
		fileSystemEqualityState.setFirstAtsAgent("192.168.0.1");
		// act
		String firstAtsAgent = fileSystemEqualityState.getFirstAtsAgent();
		// assert
		assertEquals("192.168.0.1", firstAtsAgent);
	}

}