/*
 * Copyright 2017 Axway Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test axway-java-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
ROOST_METHOD_HASH=getFirstAtsAgent_9ded35b35a
ROOST_METHOD_SIG_HASH=getFirstAtsAgent_9160efdd0c
"""
  Scenario 1: Test when getFirstAtsAgent returns null

  Details:
    TestName: testGetFirstAtsAgentWhenNull
    Description: This test is meant to check if the getFirstAtsAgent() method correctly returns null when 'firstAtsAgent' variable is not set.
  Execution:
    Arrange: Do not set any value to the 'firstAtsAgent' variable.
    Act: Invoke getFirstAtsAgent() method.
    Assert: Assert that the expected value is null.
  Validation:
    The assertion aims to verify that the 'getFirstAtsAgent' method correctly returns null when 'firstAtsAgent' variable is not set, as per application behavior.
  Scenario 2: Test when getFirstAtsAgent returns a string.

  Details:
    TestName: testGetFirstAtsAgentWhenNotNull
    Description: This test is meant to check if the getFirstAtsAgent() method correctly returns the 'firstAtsAgent' string when it is set.
  Execution:
    Arrange: Set a value to the 'firstAtsAgent' variable.
    Act: Invoke getFirstAtsAgent() method.
    Assert: Assert that the expected value is the same as the 'firstAtsAgent' value.
  Validation:
    The assertion aims to verify that the 'getFirstAtsAgent' method correctly returns the 'firstAtsAgent' string when it is set, as per application behavior.
  Scenario 3: Test when getFirstAtsAgent returns an empty string.
  Details:
    TestName: testGetFirstAtsAgentWhenEmpty
    Description: This test is meant to check if the getFirstAtsAgent() method correctly returns an empty string when 'firstAtsAgent' is set to empty.
  Execution:
    Arrange: Set 'firstAtsAgent' to an empty string.
    Act: Invoke getFirstAtsAgent() method.
    Assert: Assert that the returned string is empty.
  Validation:
    The assertion aims to verify that the 'getFirstAtsAgent' method correctly returns an empty string when 'firstAtsAgent' is not initialized. This ensures the consistent behavior of the method under different conditions.
  """
*/
// ********RoostGPT********
package com.axway.ats.common.filesystem.snapshot.equality;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.axway.ats.common.PublicAtsApi;
import org.junit.jupiter.api.*;

@Tag("com.axway.ats.common.filesystem.snapshot.equality")
@Tag("com.axway.ats.common.filesystem.snapshot.equality.getFirstAtsAgent")
public class FileSystemEqualityStateGetFirstAtsAgentTest {

	private FileSystemEqualityState fileSystemEqualityState;

	@BeforeEach
	public void setup() {
		fileSystemEqualityState = new FileSystemEqualityState("First Snapshot", "Second Snapshot");
	}

	@Test
	@Tag("valid")
	public void testGetFirstAtsAgentWhenNull() {
		String result = fileSystemEqualityState.getFirstAtsAgent();
		assertNull(result);
	}

	@Test
	@Tag("valid")
	public void testGetFirstAtsAgentWhenNotNull() {
		fileSystemEqualityState.firstAtsAgent = "Agent1";
		String result = fileSystemEqualityState.getFirstAtsAgent();
		assertEquals("Agent1", result);
	}

	@Test
	@Tag("valid")
	public void testGetFirstAtsAgentWhenEmpty() {
		fileSystemEqualityState.firstAtsAgent = "";
		String result = fileSystemEqualityState.getFirstAtsAgent();
		assertEquals("", result);
	}

}