/*
 * Copyright 2017-2020 Axway Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test axway-java-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
ROOST_METHOD_HASH=getTablesWithRowsPresentInOneSnapshotOnly_a140bcad39
ROOST_METHOD_SIG_HASH=getTablesWithRowsPresentInOneSnapshotOnly_fe2c8cdc18
"""
  Scenario 1: Test when the snapshot is null
  Details:
    TestName: testForNullSnapshot
    Description: The test is intended to check the method's handling when passed a null snapshot name.
  Execution:
    Arrange: Set the snapshot parameter to null.
    Act: Call the method getTablesWithRowsPresentInOneSnapshotOnly with the null parameter.
    Assert: Expect an IllegalArgumentException or a NullPointer exception.
  Validation:
    The method should correctly handle null inputs for the snapshot name, as they cannot be processed. This test ensures the robustness of the application against faulty or missing data.
  Scenario 2: Test for an empty snapshot name.
  Details:
    TestName: testForEmptySnapshotName
    Description: The test checks the method's behavior when passed an empty snapshot name.
  Execution:
    Arrange: Set the snapshot parameter as an empty string ("").
    Act: Invoke the method getTablesWithRowsPresentInOneSnapshotOnly with the empty string.
    Assert: Expect handling for invalid input - possibly an IllegalArgumentException or a specific error message.
  Validation:
    The method should handle invalid parameters such as empty strings correctly to prevent misinterpretation of data. This test verifies this functionality.

  Scenario 3: Test when the snapshot name is not present in the map rowPresentInOneSnapshotOnly.
  Details:
    TestName: testForNonExistingSnapshotName
    Description: The test is intended to verify the method's handling when the snapshot name is not present in the map rowPresentInOneSnapshotOnly.
  Execution:
    Arrange: Set the snapshot name as a non-existing key in the rowPresentInOneSnapshotOnly map.
    Act: Invoke the method getTablesWithRowsPresentInOneSnapshotOnly with the input snapshot name.
    Assert: Return an empty list as there are no matching tables with unique rows for the given snapshot name.
  Validation:
    The method should return an empty list rather than throwing an error when the snapshot name is present. This test certifies the graceful handling of this scenario.
  Scenario 4: Test when the snapshot name is present in the map rowPresentInOneSnapshotOnly.
  Details:
    TestName: testForExistingSnapshotName
    Description: The test is meant to verify that the method works correctly when the snapshot name is present in the rowPresentInOneSnapshotOnly map and can get the list of tables with unique rows.
  Execution:
    Arrange: set the snapshot name as a key that is present in the rowPresentInOneSnapshotOnly map.
    Act: Invoke the method getTablesWithRowsPresentInOneSnapshotOnly with the snapshot name.
    Assert: The returned list should match the data mapped to the snapshot name in rowPresentInOneSnapshotOnly.
  Validation:
    The test verifies that the method correctly retrieves and returns the tables with unique rows when a snapshot name is given which exists in the rowPresentInOneSnapshotOnly map.
  Scenario 5: Test for a case-insensitive match.
  Details:
    TestName: testForCaseInsensitiveSnapshotName
    Description: The test checks whether the method correctly handles case differences in the snapshot name.
  Execution:
    Arrange: Set the snapshot name with a case difference from a key in rowPresentInOneSnapshotOnly map.
    Act: Invoke the method getTablesWithRowsPresentInOneSnapshotOnly with the snapshot name.
    Assert: The method should either return a list corresponding to the matched snapshot name (if the application supports a case-insensitive policy) or an empty list (if it does not).
  Validation:
    The test ensures the method’s robustness and compatibility with snapshot names having different cases, enhancing its usability.
"""
*/
// ********RoostGPT********
package com.axway.ats.common.dbaccess.snapshot.equality;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import com.axway.ats.common.PublicAtsApi;
import org.junit.jupiter.api.*;

@Tag("com.axway.ats.common.dbaccess.snapshot.equality")
@Tag("com.axway.ats.common.dbaccess.snapshot.equality.getTablesWithRowsPresentInOneSnapshotOnly")
@Tag("com.axway.ats.common.dbaccess.snapshot.equality.breakIntoTables")
public class DatabaseEqualityStateGetTablesWithRowsPresentInOneSnapshotOnlyTest {

	private DatabaseEqualityState databaseEqualityState;

	private String testSnapshotKey = "testSnapshot";

	private Map<String, Map<String, List<String>>> testRowPresentInOneSnapshotOnly = new HashMap<>();

	@BeforeEach
	public void setup() {
		List<String> tables = new ArrayList<>();
		tables.add("table1");
		tables.add("table2");
		Map<String, List<String>> tableMap = new HashMap<>();
		tableMap.put(testSnapshotKey, tables);
		testRowPresentInOneSnapshotOnly.put(testSnapshotKey, tableMap);
		databaseEqualityState = new DatabaseEqualityState(testSnapshotKey, "secondSnapshot");
		databaseEqualityState.rowPresentInOneSnapshotOnly = testRowPresentInOneSnapshotOnly;
	}

	@Test
	@Tag("invalid")
	public void testForNullSnapshot() {
		Assertions.assertThrows(IllegalArgumentException.class, () -> {
			databaseEqualityState.getTablesWithRowsPresentInOneSnapshotOnly(null);
		});
	}

	@Test
	@Tag("invalid")
	public void testForEmptySnapshotName() {
		Assertions.assertThrows(IllegalArgumentException.class, () -> {
			databaseEqualityState.getTablesWithRowsPresentInOneSnapshotOnly("");
		});
	}

	@Test
	@Tag("valid")
	public void testForNonExistingSnapshotName() {
		List<String> expectedResult = new ArrayList<>();
		Assertions.assertEquals(expectedResult,
				databaseEqualityState.getTablesWithRowsPresentInOneSnapshotOnly("nonExistingSnapshot"));
	}

	@Test
	@Tag("valid")
	public void testForExistingSnapshotName() {
		List<String> expectedResult = new ArrayList<>();
		expectedResult.addAll(databaseEqualityState.rowPresentInOneSnapshotOnly.get(testSnapshotKey).keySet());
		Assertions.assertEquals(expectedResult,
				databaseEqualityState.getTablesWithRowsPresentInOneSnapshotOnly(testSnapshotKey));
	}

	@Test
	@Tag("boundary")
	public void testForCaseInsensitiveSnapshotName() {
		List<String> expectedResult = new ArrayList<>();
		Assertions.assertEquals(expectedResult,
				databaseEqualityState.getTablesWithRowsPresentInOneSnapshotOnly("TESTSNAPSHOT"));
	}

}